console.log("===========swap two variable values=============");
var sweety="sweety";
var cutie="cutie";
console.log("before swaping sweety=",sweety,"and cutie=",cutie);
var temp;
temp=sweety;
sweety=cutie;
cutie=temp;
console.log("after  swaping sweety=",sweety,"and cutie=",cutie);
console.log("");
console.log("===========Swap three variable values=============");
var num1=100;
var num2=200;
var num3=300;
var temp;
console.log("before swaping num1=",num1,",num2= ",num2,"and num3=",num3);
temp=num1;
num1=num2;
num2=num3;
num3=temp;
console.log("after  swaping num1=",num1,",num2= ",num2,"and num3=",num3);