var myFullName;
console.log(myFullName);
myFullName="Smith Nakhwa";
console.log(myFullName);
myFullName="Smith sachin nakhwa";
console.log(myFullName);
var myLove="i love only JS";
console.log(myLove);
var firstName="firstname:-Smith";
var lastName="lastname:-Nakhwa";
var age="22";
var address="Address:-R/o:-Karanja Navapada,Uran";
var pincode="pincode:-400-702";
var gender="gender:-Male";
var is_Married="is_married:-No";
console.log(firstName);
console.log(lastName);
console.log(age);
console.log(address);
console.log(pincode);
console.log(gender);
console.log(is_Married);
var name =true;
console.log(typeof name );
console.log(typeof name );

