var myFullName;
console.log(myFullName);
myFullName="Smith Nakhwa";
console.log(myFullName);
myFullName="Smith sachin nakhwa";
console.log(myFullName);
var myLove="i love only JS";
console.log(myLove);
var firstName="Smith";
var lastName="Nakhwa";
var age="22";
var address="R/o:-Karanja Navapada,Uran";
var pincode="400-702";
var gender="Male";
var is_married="No";
console.log(firstName);
console.log(lastName);
console.log(age);
console.log(address);
console.log(pincode);
console.log(gender);
console.log(is_married);

